# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\D-DRIVE\EDP\pannellum\Plugin\2.0\panostreetview_2\PanoStreetView_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PanoStreetView_2DialogBase(object):
    def setupUi(self, PanoStreetView_2DialogBase):
        PanoStreetView_2DialogBase.setObjectName("PanoStreetView_2DialogBase")
        PanoStreetView_2DialogBase.resize(441, 301)
        self.gridLayout_2 = QtWidgets.QGridLayout(PanoStreetView_2DialogBase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(PanoStreetView_2DialogBase)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_2.addWidget(self.lineEdit_1)
        self.toolButton_1 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_1.setObjectName("toolButton_1")
        self.horizontalLayout_2.addWidget(self.toolButton_1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(self.groupBox)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout.addWidget(self.button_box)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(PanoStreetView_2DialogBase)
        self.button_box.accepted.connect(PanoStreetView_2DialogBase.accept)
        self.button_box.rejected.connect(PanoStreetView_2DialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(PanoStreetView_2DialogBase)

    def retranslateUi(self, PanoStreetView_2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        PanoStreetView_2DialogBase.setWindowTitle(_translate("PanoStreetView_2DialogBase", "PanoStreetView_2"))
        self.groupBox.setTitle(_translate("PanoStreetView_2DialogBase", "Inputs"))
        self.label.setText(_translate("PanoStreetView_2DialogBase", "Path to Shapefile:"))
        self.toolButton_1.setText(_translate("PanoStreetView_2DialogBase", "..."))
        self.label_2.setText(_translate("PanoStreetView_2DialogBase", "Path to Images:"))
        self.toolButton_2.setText(_translate("PanoStreetView_2DialogBase", "..."))
        self.pushButton.setText(_translate("PanoStreetView_2DialogBase", "Add Index"))
