# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PanoStreetView_2
                                 A QGIS plugin
 PanoStreetView_2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Sachin Kulal
        email                : sachinmk1998@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QLabel

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .PanoStreetView_2_dialog import PanoStreetView_2Dialog
import os.path


# Addtional libraries
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from qgis.PyQt.QtWidgets import QAction, QFileDialog
import math
import json
import webbrowser
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse
from qgis.PyQt import QtCore
import requests
import shutil


# global variables
shapefile_path = None
image_folder = None
point_layer = None
index = None
nearest_finder = None

angle = 0
premuto = False
linea = False
HOST, PORT = "", 8030

chrome_path = "C:/Program Files/Google/Chrome/Application/chrome.exe"
base_folder = os.path.dirname(os.path.realpath(__file__))

rb = QgsRubberBand(iface.mapCanvas(),QgsWkbTypes.PointGeometry)
marker = QgsVertexMarker(iface.mapCanvas())
rl = QgsRubberBand(iface.mapCanvas(),QgsWkbTypes.LineGeometry)

point0 = iface.mapCanvas().getCoordinateTransform().toMapCoordinates(0, 0)
point1 = iface.mapCanvas().getCoordinateTransform().toMapCoordinates(0, 0)

class PanoStreetView_2:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PanoStreetView_2_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&PanoStreetView_2')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PanoStreetView_2', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/PanoStreetView_2/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'PanoStreetView_2'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&PanoStreetView_2'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_shapefile(self):
        file_name, __filter = QFileDialog.getOpenFileName(
            self.dlg, "Select shapefile Path", "", '*.shp'
        )
        if file_name:
            self.dlg.lineEdit_1.setText(file_name)
            global shapefile_path
            shapefile_path = file_name
            QgsMessageLog.logMessage("Shapefile selected")

    # funtion to select the image folder
    def select_image_path(self):
        folder_path = QFileDialog.getExistingDirectory(
            self.dlg, "Select Images Folder Path"
        )
        if folder_path:
            self.dlg.lineEdit_2.setText(folder_path)
            global image_folder
            image_folder = folder_path
            QgsMessageLog.logMessage("Image foder selected")


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.dlg = PanoStreetView_2Dialog()
            # add inputs
            self.dlg.toolButton_1.clicked.connect(self.select_shapefile)
            self.dlg.toolButton_2.clicked.connect(self.select_image_path)
            # progress bar adding index
            global nearest_finder
            nearest_finder = NearestPointFinder()  # Create an instance of NearestPointFinder
            self.dlg.pushButton.clicked.connect(lambda: nearest_finder.add_index_to_shp(self.dlg.progressBar))
            # show the dialog
            self.dlg.show()
            # Run the dialog event loop
            result = self.dlg.exec_()
            # See if OK was pressed
            self.first_start = False
            self.check = True

        if self.check:
            self.check = False
        else:
            if shapefile_path is not None:
                tool = PointTool(self.iface.mapCanvas())
                QgsMessageLog.logMessage("Point tool is called")
                self.iface.mapCanvas().setMapTool(tool)
                

# class for event in qgis canvas
class PointTool(QgsMapTool):

        def __init__(self, canvas):
            QgsMapTool.__init__(self, canvas)
            self.canvas = canvas
            self.point_coordinate = None
            self.image_path = None
            

        
        def canvasPressEvent(self, event):
            x = event.pos().x()
            y = event.pos().y()
            global rb, premuto, point0, marker
            if not premuto:
                premuto = True
                rb = QgsRubberBand(iface.mapCanvas(),QgsWkbTypes.PointGeometry)
                rb.setColor(QtCore.Qt.cyan)
                # rb_2 = QgsRubberBand(iface.mapCanvas(),QgsWkbTypes.PointGeometry)
                # rb_2.setColor(QtCore.Qt.red)
                point0 = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)
                rb.addPoint(point0)
                # rb_2.addPoint(point0)
                QgsMessageLog.logMessage("First point selected")
                self.point_coordinate = "#" + str(point0)
                QgsMessageLog.logMessage(f"Selected point is {self.point_coordinate}")
                print(f"Selected point is {self.point_coordinate}")
                marker.hide()
                # Set marker as plus symbol
                marker.setCenter(point0)  # Set the center point for the marker
                marker.setColor(QtCore.Qt.red)  # Set the color of the marker (red)
                marker.setIconType(QgsVertexMarker.ICON_CROSS)  # Set the icon type to cross (plus symbol)
                marker.setIconSize(15)  # Adjust the size of the plus symbol as needed
                marker.setPenWidth(2)  # Set the thickness of the marker
                marker.show()
                
                

        def canvasMoveEvent(self, event):
            x = event.pos().x()
            y = event.pos().y()
            global premuto, point0, point1, linea, rl
            if premuto:
                if not linea:
                    rl.setColor(QtCore.Qt.cyan)
                    point1 = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)
                    rl.reset(QgsWkbTypes.LineGeometry)
                    QgsMessageLog.logMessage("Creating line")
                    rl.addPoint(point0)
                    rl.addPoint(point1)
                    QgsMessageLog.logMessage("End point selected")


        def canvasReleaseEvent(self, event):
            global premuto, linea, rb, rl, point1, point0, angle, image_folder, nearest_finder
            angle = math.atan2(point1.x() - point0.x(), point1.y() - point0.y())
            angle = math.degrees(angle)if angle>0 else (math.degrees(angle) + 180) + 180
            premuto = False
            linea = False
            actual_crs = self.canvas.mapSettings().destinationCrs()
            crsDest = QgsCoordinateReferenceSystem.fromEpsgId(4326)
            xform = QgsCoordinateTransform(actual_crs, crsDest, QgsProject.instance())
            pt1 = xform.transform(point0)
            QgsMessageLog.logMessage("Line is released")

             
            azimuth_index, img_name, azimuth = nearest_finder.find_nearest_point_with_image(self.point_coordinate)
            nearest_finder.next_11_images(self.point_coordinate)

            if not premuto and img_name is not None and image_folder is not None:
                self.image_path = os.path.join(image_folder, img_name)
                QgsMessageLog.logMessage("Name, Path, azimuth, yaw found")
                # Prepare azimuth data to write into JSON file
                azimuth_data = {"index":azimuth_index, "azimuth": azimuth, "yaw_value": angle-azimuth}

                # Write azimuth data to a JSON file (overwriting existing content)
                json_file_path = os.path.join(base_folder, 'azimuth_data.json')
                with open(json_file_path, 'w') as json_file:
                    json.dump(azimuth_data, json_file)
                pano = PanoramaViewer(self.image_path)
                QgsMessageLog.logMessage("Serving Server at 8030")
                if pano:
                    webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
                    ch_url = "http://localhost:8030/index_view.html"
                    try:
                        webbrowser.get('chrome').open(ch_url)
                        QgsMessageLog.logMessage("Image opened in browser")
                    except Exception as e:
                        print(f"Error opening browser: {e}")
                    # finally:
                    #     pano.reset_tr()
                else:
                    webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
                    ch_url = "http://localhost:8030/index_error.html"
                    try:
                        webbrowser.get('chrome').open(ch_url)
                    except Exception as e:
                        print(f"Error opening browser: {e}")
                    # finally:
                    #     pano.reset_tr()
            # pano.reset_tr()


            rl.reset()
            rb.reset()
            self.point_coordinate = None
            self.image_path = None
            self.canvas.unsetMapTool(self)

        def activate(self):
            pass

        def deactivate(self):
            pass

        def isZoomTool(self):
            return False
        
        def isTransient(self):
            return False
        
        def isEditTool(self):
            return True


class NearestPointFinder:
    def add_index_to_shp(self, progress_bar):
        # Method to find the nearest point
        global point_layer, index, shapefile_path
        point_layer = QgsVectorLayer(shapefile_path, "points", "ogr")
        if not point_layer.isValid():
            raise ValueError("Invalid layer!")
        
        total_features = point_layer.featureCount()  # Total number of features in the point layer
        if total_features > 0:
            index = QgsSpatialIndex()
            completed = 0  # Initialize completed features counter
            progress_bar.setRange(0, total_features)  # Set the range of the progress bar
            for feature in point_layer.getFeatures():
                index.addFeature(feature)
                completed += 1
                progress_bar.setValue(completed)  # Update the progress bar
        else:
            print("No features found in the point layer.")
            QgsMessageLog.logMessage("No features found in the point layer.")
        print("Index added successfully.")
        QgsMessageLog.logMessage("Index added successfully.")

    def find_nearest_point_with_image(self, point_coordinate):
        if index is None:
            print("Spatial index is not initialized. Call add_index method first.")
            return None, None
        self.coords_str = point_coordinate.split('(')[1].split(')')[0]
        x, y = map(float, self.coords_str.split())
        point = QgsPointXY(x, y)

        nearest_ids = index.nearestNeighbor(point, 1)
        nearest_feature = point_layer.getFeature(nearest_ids[0])
        QgsMessageLog.logMessage("Found nearest image")
        azimuth_index = nearest_ids[0]
        point_name = nearest_feature["Name"]
        azimuth = nearest_feature["Azimuth"]
        print("Nearest image found.")

        return azimuth_index, point_name, azimuth
    
    def next_11_images(self, point_coordinate):
        if index is None:
            print("Spatial index is not initialized. Call add_index method first.")
            return None, None
        self.coords_str = point_coordinate.split('(')[1].split(')')[0]
        x, y = map(float, self.coords_str.split())
        point = QgsPointXY(x, y)

        all_index = []
        near_feature_all_dict = []

        near_id = index.nearestNeighbor(point, 1)[0]
        print(f"near_id-{near_id}")
        next_11_img_ids = index.nearestNeighbor(point, 3)
        next_11_img_ids.sort()


        QgsMessageLog.logMessage("Found near 11 points")
        # print(f"next_11_img_ids{next_11_img_ids}")

        l = 0
        for i in next_11_img_ids:
            all_index.append(i)
        print(f"sorted 11 index list-{all_index}")
        QgsMessageLog.logMessage("11 points sorted in ascending order")

        for i in all_index:
            near_feature = point_layer.getFeature(i)
            image_name = near_feature["Name"]
            azimuth = near_feature["Azimuth"]
            # Extract coordinates of the feature
            feature_geom = near_feature.geometry()
            feature_coords = feature_geom.asPoint()
            feature_x = feature_coords.x()
            feature_y = feature_coords.y()
            near_feature_dict = {"row": l, "index": i, "point_name": image_name, "azimuth": azimuth, "coordinates": str(feature_y) + ", " + str(feature_x)}
            near_feature_all_dict.append(near_feature_dict)
            l += 1
            json_file_path = os.path.join(base_folder, 'Image_to_copy.json')
            with open(json_file_path, 'w') as json_file:
                json.dump(near_feature_all_dict, json_file)
        QgsMessageLog.logMessage("Image_to_copy.json created")

class PanoramaViewer():
    def __init__(self, image_path):
        # custom attrs
        self.httpd = None
        self.httpd = HttpDaemon(self, base_folder)
        self.httpd.start()

    def reset_tr(self):
        """Reset server"""
        if self.httpd:
            self.httpd.stop()

class QuietHandler(SimpleHTTPRequestHandler):
    """Web server handler, which will not write any message
    in python console. As a result, no need to open python console
    in QGIS in order to make plugin work
    """

    def log_message(self, format, *args):
        pass

class HttpDaemon(QtCore.QThread):
    """Simple web server class
    """

    def __init__(self, parent, path):
        super(QThread, self).__init__()
        self.server_path = path
        self.server = None  # Initialize server attribute
        self.image_folder = image_folder  # Store the original image folder path

    def run(self):
        os.chdir(self.server_path)
        # Create a custom handler that can serve files from the image folder
        class CustomHandler(QuietHandler):
            def translate_path(self, path):
                # If the path starts with /images/, serve from the original image folder
                if path.startswith('/images/'):
                    image_name = path[8:]  # Remove '/images/' prefix
                    return os.path.join(self.server.image_folder, image_name)
                return super().translate_path(path)

        self.server = HTTPServer((HOST, PORT), CustomHandler)
        self.server.image_folder = self.image_folder  # Pass image folder to handler
        self.server.serve_forever()
        QgsMessageLog.logMessage("Serving server")

    def stop(self):
        if self.server:
            self.server.shutdown()
            self.server.socket.close()
            QgsMessageLog.logMessage("Closing socket")

    def __del__(self):
        self.stop()  # Ensure server is stopped and socket is closed when instance is deleted
        QgsMessageLog.logMessage("Server stopped")
